### ISSUE TITLE
Customer doesn't have the privileges to fetch its own vouchers

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#48]
What the title says. See here:

<img width="1082" alt="Screenshot 2024-12-26 at 21 22 42" src="https://github.com/user-attachments/assets/a472d175-cbbb-43f2-ae80-520c8634b4c3" />

**Comment by LuchsHub** [comment]
The reason for this is the voucher routes requiring the currently active user to be an employee.
(see https://github.com/53845714nF/EventTom/blob/main/backend/app/api/deps.py line 53)

This API interface seems to be bugged in general though. A lot of routes deliver a 500 Internal Server Error. The route in this issue for example also delivered a 500 when I circumvented the 403 with this small hotfix: 

if not (current_user.user_type == UserType.EMPLOYEE or current_user.role == Role.ADMIN):

Trying the API interface with this hot fix caused the following error to pop up in the terminal where I docker-composed:

backend-1      | psycopg.errors.UndefinedColumn: column voucher.code_name does not exist
backend-1      | LINE 1: SELECT voucher.amount, voucher.code_name, voucher.id, vouche...

I really don't understand this error, since voucher.amount is recognised properly, but code_name isn't. @53845714nF Do you have a clue?

**Comment by 53845714nF** [comment]
Denke die Daten exestiern nicht in Datenbank guck noch mal ob sie auch wirklich in der Datenbank sind wenn du testest.

**Comment by LuchsHub** [comment]
This issue got fixed with #49.

**Comment by LuchsHub** [comment]
This issue should be fixed with PR #49.
